version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Installing dependencies or performing pre-build steps"
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - target/shopping-cart-0.0.1-SNAPSHOT.war
